### ISSUE TITLE
energy generation -> operational energy

### ISSUE THREAD

**Issue by ReimeiSky** [Elyssaen/trin#13]
Operational energy was intended to replace negative energy generation.
And yet you still have the latter.
https://github.com/Elyssaen/trin/blob/master/data/trin%20outfits.txt#L16
https://github.com/Elyssaen/trin/blob/master/data/trin%20outfits.txt#L27
https://github.com/Elyssaen/trin/blob/master/data/trin%20outfits.txt#L53
https://github.com/Elyssaen/trin/blob/master/data/trin%20outfits.txt#L105

It's clear that you *do* intend to use operational energy.
https://github.com/Elyssaen/trin/blob/master/data/trin%20outfits.txt#L278

fixplz

**Comment by Elyssaen** [comment]
Good catch! For a while I was going to try to keep OperationalEnergy unnecessary, but the Strangelet Adapter needed it (otherwise you have to do a ridiculous juggle to ever install one) and I forgot to change the others. Doing that now.

_Edit:_ Done in 94251ba216cf729d887b797739f38b1c14f6ab64.
